### ISSUE TITLE
GstISOFMP4Mux 엘리먼트 PTS 버그

### ISSUE THREAD

**Issue by DanielHa1018** [atins-dev/gstreamer#22]
**Describe the issue**
`thread '<unnamed>' panicked at 'attempt to subtract with overflow', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\core\src\ops\arith.rs:219:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ERROR mediaserver::sink::base_sink > sink(id:3) received error from element Some("/RecordBin:recordbin0/GstISOFMP4Mux:mux"): GStreamer encountered a general supporting library error. (Some("C:\\Users\\user\\.cargo\\git\\checkouts\\gstreamer-rs-79e52a2d27eb91a3\\c1459c1\\gstreamer-base\\src\\subclass\\aggregator.rs(876): gstreamer_base::subclass::aggregator (): /RecordBin:recordbin0/GstISOFMP4Mux:mux:\nPanicked: attempt to subtract with overflow"))
 ERROR at_nvr::app                  > Error received: sink error `Sink(`3`) unknown failure, details: `GStreamer encountered a general supporting library error.```

1. ignis-app에서 녹화 하다가 보면 pts 계산이 - 가 되어서 되는 버그로 추정됨.

**To Reproduce**
특정 재현 조건은 모르고, 테스트하다가 처음 패닉이 뜨면서 죽었음.

**Comment by powerory** [comment]
```
Some(i64::try_from((pts - dts).nseconds()).map_err(|_| {
                    gst::error!(CAT, obj: stream.sinkpad, "Too big PTS/DTS difference");
                    gst::FlowError::Error
                })?)
```
해당 부분의 pts-dts에서 발생하는 문제로 추정됨

**Comment by powerory** [comment]
main branch는 아래와 같이 가드 코드가 달려있는 듯 하다.
```
                Some(
                    i64::try_from(
                        (gst::Signed::Positive(pts) - gst::Signed::Positive(dts)).nseconds(),
                    )
                    .map_err(|_| {
                        gst::error!(CAT, obj: stream.sinkpad, "Too big PTS/DTS difference");
                        gst::FlowError::Error
                    })?,
                )

```

**Comment by powerory** [comment]
https://github.com/atins-dev/gst-plugins-rs/commit/d61320420ad4902de1de4a62c3afd131f0b6f30c
plugins-rs에 해당 패치를 적용해놓았음.

그 이후에도 재발되는지는 테스트 필요.

**Comment by powerory** [comment]
더이상 재현되지 않아 close합니다.
